<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="login"
    targetNamespace="http://localhost/"
    xmlns="http://localhost"
    xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">


    <wsdl:message name="request">
        <wsdl:part name="uname" type="xs:string"/>
        <wsdl:part name="pasword" type="xs:string"/>
        
    </wsdl:message>

    <wsdl:message name="response">
        <wsdl:part name="good" type="xs:boolean"/>
        <wsdl:part name="id" type="xs:integer"/>
    </wsdl:message>

    <wsdl:portType name="llogin">

        <wsdl:operation name="send">
            <wsdl:input message="request"/>
            <wsdl:output message="response"/>
        </wsdl:operation>

    </wsdl:portType>

    <wsdl:binding name="loginSoapBinding" type="llogin">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

        <wsdl:operation name="send">
            <soap:operation soapAction="send"/>
            <wsdl:input>
                <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        
    </wsdl:binding>
    <wsdl:service name="loginService">
        <wsdl:port binding="loginSoapBinding" name="loginPort">
            <soap:address location="http://localhost:8000/Emok"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
